name: Daily Task Update

on:
  schedule:
    # 每天北京时间早上9点运行
    - cron: '0 1 * * *'
  # 允许手动触发
  workflow_dispatch:

jobs:
  update-tasks:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tools/notion_integration/requirements.txt
    
    - name: Run daily update
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        DATABASE_ID: ${{ secrets.DATABASE_ID }}
      run: |
        cd tools/notion_integration
        python daily_update.py
    
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git diff --quiet && git diff --staged --quiet || \
          (git commit -m "chore: update task status [skip ci]" && \
           git push)
